### ISSUE TITLE
Create a generated facet for places missing coordinates (not mappable)

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#144]

**Comment by esjewett** [comment]
So, for each coordinates dimension there should now be a dimension called "[Name of coordinates dimension]: Exists". This dimension will have value true if it exists and false if not. It can be used in the facet filter or in the timeline as a grouping. You can try this on the sample data set and you will see that even there there are many missing coordinates (all because of missing places of death).

**Comment by esjewett** [comment]
Let me know how this is looking and if we need updates or changes?

**Comment by esjewett** [comment]
Looks like this may not be working for the Voltaire data. I'll keep this issue open for the moment.

**Comment by esjewett** [comment]
Ok, I think we're in business now.
