### ISSUE TITLE
stuck on loading

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#32]
The console shows this error:
Uncaught TypeError: Cannot read property 'map' of undefined

Loaded 3 tables. The application hangs on the data page. It won't move to any view page.

**Comment by esjewett** [comment]
That's not good. Does this happen for you with the sample data? It isn't happening with the sample data for me, so I'm wondering if there is something specific in the data-set you are using that is making something go wrong.

Also, can you paste the full console output with line numbers? Then I'll be able to track down exactly where the issue is happening and may be able to figure out how to recreate it from there. Thanks!
