### ISSUE TITLE
Add a class to the graph component for border styling

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/palladio#96]

**Comment by esjewett** [comment]
It should work to style the containing element instead. e.g.

```html
<div id="graph-view-here" style="border: medium solid black;"></div>
```

Or it's possible to style all graph views with CSS using

```css
[data-palladio-graph-view] {
	border: medium solid black;
}
```

Generally speaking, this CSS-based approach is what should be used to over-ride styles for the visualization components. It should be possible to use selectors based on container elements to style the same component differently at different places on a single page.

**Comment by cncoleman** [comment]
I would rather not have styles inline. I did add a "bordered" class to the component display div (since we may want other components bordered at times-- not graph-specific) but There was a big margin around the graph inside the border. Somehow I missed the margin 40px added in the standalone.css

**Comment by esjewett** [comment]
Happens to me as well. Our CSS rules are a bit scattered around.






On Sun, Nov 1, 2015 at 8:27 AM -0800, "Nicole Coleman" <notifications@github.com> wrote:












I would rather not have styles inline. I did add a "bordered" class to the component display div (since we may want other components bordered at times-- not graph-specific) but There was a big margin around the graph inside the border. Somehow I missed the margin 40px added in the standalone.css
